version: '3.4'
services:
  chat:
    build: .
    depends_on:
      - redis
    ports:
      - "9080:9080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - .:/code
    links:
      - "redis"
  redis:
    image: "redis:6.0.5-alpine3.12"
    volumes:
      - redis-chat:/var/lib/redis
    ports:
      - "127.0.0.1:6379:6379"
volumes:
  redis-chat:
